### PR TITLE
Missing parent

### LINKED ISSUE #523: Suggestion:  parent should return nil instead of ActiveRecordNotFound exception.
Presently, when the `ancestry` field contains an ID, but the parent object has been deleted from the database, calling the `parent` method results in an exception. 

```ruby
user.parent = user2
user2.delete
user.parent
> ActiveRecordNotFound
```

In contrast, ActiveRecord returns nil for a `belongs_to` relation, when the foreign key has a value, but the record does not exist. 

For this example, a User "belongs_to" a Team.

```ruby
user.update_column :team_id, 123456
user.team
> nil
```
Please consider making the result of the `parent` method consistent with the handling of `belongs_to` in ActiveRecord. 

Thanks!

### PR DESCRIPTION
**Pull request by kbrock**
resolves #523

if an invalid value is in the `parent_id`, `parent` will return nil not throw error

### CODE REVIEW

**Review by d-m-u — APPROVED** [review]
do you want to merge https://github.com/stefankroes/ancestry/pull/538 before this?

File: test/concerns/relations_test.rb [hunk 1]
```diff
@@ -0,0 +1,37 @@
+require_relative '../environment'
+require 'byebug'
```
Comment (d-m-u) [inline test/concerns/relations_test.rb:2]: this line, do you need?

Comment (kbrock) [reply test/concerns/relations_test.rb:2]: JUST deleted before I saw this - thanks

File: Gemfile [hunk 2]
```diff
@@ -2,7 +2,7 @@ source 'https://rubygems.org'
 
 gemspec
 
-gem "activerecord", '~> 5.2.4.5'
+gem "activerecord", "~> 6.0.3"
```
Comment (kbrock) [inline Gemfile:5]: of note, for these we want to limit to 3 digits. the last digit is allowed to change.
So pegging to 5.2.4.5 will allow 5.2.4.6 but not 5.2.5.
